name: Build and Upload Release JAR

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile Java source files
        run: |
          mkdir -p out/classes
          javac -d out/classes $(find src -name "*.java")

      - name: Create JAR file
        run: |
          jar --create --file out/Snake-Game.jar -C out/classes .

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/Snake-Game.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
