name: Build and Upload Release JAR

on:
  release:
    types: [created]

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile Java source files
        run: |
          mkdir -p out/classes
          javac -d out/classes $(find src -name "*.java")

      - name: Create manifest file
        run: |
          echo "Main-Class: com.pandavoid.snakegame.Main" > manifest.txt

      - name: Create JAR file
        run: |
          jar --create --file out/Snake-Game.jar --manifest manifest.txt -C out/classes .
      - name: Create ZIP with JAR and assets folder
        run: |
          mkdir dist
          cp out/Snake-Game.jar dist/
          cp -r assets dist/
          cd dist
          zip -r ../Snake-Game.zip *

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: Snake-Game.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}