name: Build Release / Alpha

on:
  release:
    types: [created]
  push:
    tags:
      - 'alpha-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - run: |
          mkdir -p out/classes
          javac -d out/classes $(find src -name "*.java")

      - run: |
          jar --create --file out/Snake-Game.jar -C out/classes .

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/Snake-Game.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
