name: Java Build

on:
  release:
    types: [ created ]
  push:
    tags:
      - 'alpha-*'
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile Java source files
        run: |
          mkdir -p out/classes
          javac -d out/classes $(find src -name "*.java")

      - name: Create JAR file
        run: |
          jar --create --file out/Snake-Game.jar -C out/classes .

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: Snake-Game-jar
          path: out/Snake-Game.jar